app/models/__init__.py
from .user import User

app/models/user.py
from datetime import datetime

from flask_login import UserMixin
from werkzeug.security import generate_password_hash

from app import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    email = db.Column(db.String(80), unique=True, nullable=False)
    _password = db.Column("password", db.Text, nullable=False)
    public_key = db.Column(db.Text, nullable=True)
    otp = db.Column(db.Text, nullable=True)
    otp_created_at = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, onupdate=datetime.utcnow)

    def __repr__(self):
        return "User: {}".format(self.name)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, password):
        self._password = generate_password_hash(password)

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
login_manager.login_view = "home.index"


def create_app(config="app.config.ProductionConfig"):
    app = Flask(__name__)
    app.config.from_object(config)
    db.init_app(app)

    migrate.init_app(app, db, directory="app/db/migrations")

    from app.models import User
    from app.views.home import home

    login_manager.init_app(app)

    app.register_blueprint(home)

    return app

app/views/home/__init__.py
from .routes import home

app/views/home/routes.py
from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from pureauth_sdk import exceptions, generate_ecies_qr, load_public_key
from werkzeug.security import check_password_hash

from app import db
from app.models import User

home = Blueprint("home", __name__)


@home.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        email = request.form.get("email")
        user = User.query.filter_by(email=email).first()
        if user:
            if "password-login" in request.form:
                return redirect(
                    url_for("home.password_login", email=request.form.get("email"))
                )
            elif "pureauth-login" in request.form:
                if user.public_key:
                    return redirect(
                        url_for("home.pureauth_login", email=request.form.get("email"))
                    )
                else:
                    flash(
                        "Public Key missing! To use PureAuth authentication upload your public key first using Password Login"
                    )
            else:
                pass
        else:
            flash("User not exists!")

    return render_template("home/index.html")


@home.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        name = request.form.get("name")
        email = request.form.get("email")
        password = request.form.get("password")

        email_check = User.query.filter_by(email=email).first()

        if email_check:
            flash("User already exists")
        else:
            user = User(name=name, email=email, password=password)
            db.session.add(user)
            db.session.commit()

            flash("User added Successfully!")
            return redirect(url_for("home.index"))

    else:
        if current_user.is_authenticated:
            return redirect(url_for("home.index"))

    return render_template("home/register.html")


@home.route("/auth/password", methods=["GET", "POST"])
def password_login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        email_user = User.query.filter_by(email=email).first()
        if email_user:
            password_user = check_password_hash(email_user.password, password)

            if password_user:
                login_user(email_user)
                return redirect(url_for("home.dashboard"))
            else:
                flash("Wrong Credentials!")
        else:
            flash("User not exists!")

    else:
        if current_user.is_authenticated:
            return redirect(url_for("home.dashboard"))

        if request.args.get("email") is None:
            flash("Please enter your Email ID")
            return redirect(url_for("home.index"))

    return render_template("home/password_login.html")


@home.route("/auth/pureauth", methods=["GET", "POST"])
def pureauth_login():
    if request.method == "POST":
        email = request.form.get("email")
        otp = request.form.get("otp")
        user = User.query.filter_by(email=email, otp=otp).first()
        if user:
            login_user(user)
            return redirect(url_for("home.dashboard"))
        else:
            flash("Wrong Credentails")
            return redirect(url_for("home.index"))
    else:
        if current_user.is_authenticated:
            return redirect(url_for("home.dashboard"))

        if request.args.get("email") is None:
            flash("Please enter Email ID")
            return redirect(url_for("home.index"))
        email = request.args.get("email")
        qr_user = User.query.filter_by(email=email).first()
        qr_code_data = generate_ecies_qr(qr_user.public_key)
        qr_user.otp = qr_code_data[1].decode("utf-8")
        qr_user.otp_created_at = datetime.utcnow()

        db.session.add(qr_user)
        db.session.commit()

    return render_template("home/pureauth_login.html", qr_code=qr_code_data[0])


@home.route("/dashboard", methods=["GET", "POST"])
@login_required
def dashboard():
    if request.method == "POST":
        public_key = request.form.get("public_key")
        try:
            load_public_key(public_key)
            user = User.query.get(current_user.id)
            user.public_key = public_key
            db.session.add(user)
            db.session.commit()
            flash("Public Key uploaded successfully!")
        except exceptions.InvalidECPublicKey:
            flash("Unable to upload Public Key")

    return render_template("home/dashboard.html")


@home.route("/auth/logout")
def logout():
    logout_user()
    return redirect(url_for("home.index"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_title %} {% endblock %}</title>

    <!-- Load Styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">

    {% block extra_css %}
    {% endblock %}
</head>

<body id="page-top">
    <!-- Include menu -->
    {% include 'menu.html' %}

    {% block content %}

    {% endblock %}

    <!-- Load Scripts -->
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/custom.js') }}"></script>
</body>

</html>

app/templates/home/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block page_title %}Admin Dashboard {% endblock %}</title>

  {% block extra_css %}
  <!-- Custom fonts for this template-->
  <!-- <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"> -->
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}" rel="stylesheet">

  {% endblock %}

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url_for('home.index') }}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Volon</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('home.dashboard') }}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider my-0">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('home.logout') }}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Logout</span></a>
      </li>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <!-- <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form> -->

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ current_user.name }}</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <!-- <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div> -->
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
          </div>

          {% with messages = get_flashed_messages() %}
          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-primary">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}


          <div class="row">

            <!-- Area Chart -->
            <div class="col-xl-8 col-lg-7">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Upload your public key</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <form action="{{ url_for('home.dashboard') }}" method="post">
                    <div class="form-group">
                      <textarea class="form-control" rows="5" name="public_key" placeholder="Paste your public key here"
                        autofocus
                        required>{% if current_user.public_key %}{{ current_user.public_key }}{% endif %}</textarea>
                    </div>
                    <div class="input-group">
                      <input type="submit" class="btn btn-primary" value="Submit">
                    </div>
                  </form>
                </div>
              </div>
            </div>



          </div>
          <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Dashboard 2020</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->

      </div>
      <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="login.html">Logout</a>
          </div>
        </div>
      </div>
    </div>
</body>

</html>

app/templates/home/index.html
{% extends 'base.html' %}

{% block page_title %} Home Page {% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image" data-background="{{ url_for('static', filename='img/background.jpeg') }}"></div>
        <div class="col-md-8 col-lg-6">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9 col-lg-8 mx-auto">
                            {% if current_user.is_authenticated %}
                            <h3 class="login-heading mb-4">Welcome, {{ current_user.name }}</h3>
                            <a href="{{ url_for('home.dashboard') }}" class="btn btn-primary">Go to Dashboard</a>
                            {% else %}
                            <h3 class="login-heading mb-4">Welcome back!</h3>
                            {% with messages = get_flashed_messages() %}
                            {% if messages %}
                            {% for message in messages %}
                            <div class="alert alert-primary">
                                {{ message }}
                            </div>
                            {% endfor %}
                            {% endif %}
                            {% endwith %}
                            <form method="POST" action="">
                                {{ csrf_token }}
                                <div class="form-label-group mb-3">
                                    <input type="email" id="inputEmail" name="email" class="form-control"
                                        placeholder="Email address" required autofocus>
                                    <label for="inputEmail">Email address</label>
                                </div>
                                <div class="row">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                                        <input
                                            class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2"
                                            type="submit" name="password-login" value="Login with Password" />
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                                        <input
                                            class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2"
                                            type="submit" name="pureauth-login" value="Login with PureAuth" />
                                    </div>
                                </div>
                            </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/home/password_login.html
{% extends 'base.html' %}

{% block page_title %} Login with Password {% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image" data-background="{{ url_for('static', filename='img/background.jpeg') }}"></div>
        <div class="col-md-8 col-lg-6">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9 col-lg-8 mx-auto">
                            <h3 class="login-heading mb-4">Login with Password</h3>
                            {% with messages = get_flashed_messages() %}
                            {% if messages %}
                            {% for message in messages %}
                            <div class="alert alert-primary">
                                {{ message }}
                            </div>
                            {% endfor %}
                            {% endif %}
                            {% endwith %}
                            <form method="POST" action="">
                                <div class="form-label-group mb-3">
                                    <input type="email" id="inputEmail" value="{{ request.args.email }}" name="email"
                                        class="form-control" placeholder="Email address" required>
                                    <label for="inputEmail">Email address</label>
                                </div>

                                <div class="form-label-group">
                                    <input type="password" id="inputPassword" class="form-control"
                                        placeholder="Password" name="password" required autofocus>
                                    <label for="inputPassword">Password</label>
                                </div>
                                <div class="row">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                                        <input
                                            class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2"
                                            type="submit" value="Login" />
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                                        <a class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2"
                                            href="{{ url_for('home.index') }}">Back</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/home/pureauth_login.html
{% extends 'base.html' %}

{% block page_title %} Login with PureAuth {% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image" data-background="{{ url_for('static', filename='img/background.jpeg') }}"></div>
        <div class="col-md-8 col-lg-6">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9 col-lg-8 mx-auto">
                            <h3 class="login-heading mb-4">Login with PureAuth</h3>

                            <form method="POST" action="{{ url_for('home.pureauth_login') }}">
                                <h5>Login for <strong>{{ request.args.email }}</strong></h5>
                                <input type="hidden" name="email" value="{{ request.args.email }}">
                                <div class="row">
                                    <div class="offset-xl-3 offset-lg-3 offset-md-3 col-xl-6 col-lg-6 col-md-6 col-12">
                                        <div class="pi-qr-wrapper">
                                            <!-- <img src="{{ url_for('static', filename='img/qrcode.png') }}"
                                                style="width: 100%;" alt=""> -->
                                            <img src="data:image/png;base64, {{ qr_code }}" style="width: 100%;" alt="">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-label-group">
                                    <input type="password" id="inputOTP" class="form-control" placeholder="OTP"
                                        name="otp" required autofocus>
                                    <label for="inputOTP">Enter OTP</label>
                                </div>
                                <div class="row">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                                        <button
                                            class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2"
                                            type="submit">Login</button>
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                                        <a class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2"
                                            href="{{ url_for('home.index') }}">Back</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/home/register.html
{% extends 'base.html' %}

{% block page_title %}Register {% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image" data-background="{{ url_for('static', filename='img/background.jpeg') }}"></div>
        <div class="col-md-8 col-lg-6">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9 col-lg-8 mx-auto">
                            <h3 class="login-heading mb-4">Register</h3>
                            {% with messages = get_flashed_messages() %}
                            {% if messages %}
                            {% for message in messages %}
                            <div class="alert alert-primary">
                                {{ message }}
                            </div>
                            {% endfor %}
                            {% endif %}
                            {% endwith %}
                            <form method="POST" action="{{ url_for('home.register') }}">
                                <div class="form-label-group mb-3">
                                    <input type="text" id="inputName" name="name" class="form-control"
                                        placeholder="Name" required autofocus>
                                    <label for="inputName">Name</label>
                                </div>
                                <div class="form-label-group mb-3">
                                    <input type="email" id="inputEmail" name="email" class="form-control"
                                        placeholder="Email address" required>
                                    <label for="inputEmail">Email address</label>
                                </div>

                                <div class="form-label-group">
                                    <input type="password" id="inputPassword" class="form-control"
                                        placeholder="Password" name="password" required>
                                    <label for="inputPassword">Password</label>
                                </div>
                                <div class="row">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                                        <button
                                            class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2"
                                            type="submit">Register</button>
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                                        <a class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2"
                                            href="{{ url_for('home.index') }}">Back</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/menu.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('home.index') }}"><strong>Volon</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('home.logout') }}">Logout
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('home.register') }}">Register
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>